In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

In [3]:
from sklearn.externals import joblib
from classification_report_dataframe import classification_report_df, f1_score_class_1_2

In [4]:
scale_max = pd.read_csv('hypodata_max_for_scaling.csv')

In [5]:
scale_max

age    TSH    T3    TT4   T4U    FTI
0  94.0  478.0  10.6  430.0  2.12  395.0

In [6]:
scale_max.values

array([[ 94.  , 478.  ,  10.6 , 430.  ,   2.12, 395.  ]])

In [7]:
a = [[ 94.0, 478.0, 10.6,  430.1,  2.12, 395.0 ], 
     [ 94.0, 478.0, 10.6,  430.1,  2.12, 395.0 ]]
arr = np.array(a).reshape(-1, 6)

In [8]:
len(arr)

2

In [9]:
arr

array([[ 94.  , 478.  ,  10.6 , 430.1 ,   2.12, 395.  ],
       [ 94.  , 478.  ,  10.6 , 430.1 ,   2.12, 395.  ]])

In [10]:
# scale_min = pd.read_csv('hypodata_min_for_scaling.csv')

In [11]:
df_test = pd.read_csv("hypotest_numeric.csv", encoding='utf-8')

In [12]:
df_test.head()

age    TSH     T3      TT4    T4U      FTI  classes
0  35.0  4.672  2.025  109.072  0.998  110.788        0
1  63.0  3.500  2.500  108.000  0.960  113.000        0
2  25.0  4.600  2.400   61.000  0.820   75.000        0
3  53.0  0.250  2.100  145.000  1.030  141.000        0
4  92.0  0.700  1.300  120.000  0.840  143.000        0

In [13]:
df_test.columns

Index(['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI', 'classes'], dtype='object')

In [14]:
X_test = df_test[['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']]

In [15]:
X_test.head()

age    TSH     T3      TT4    T4U      FTI
0  35.0  4.672  2.025  109.072  0.998  110.788
1  63.0  3.500  2.500  108.000  0.960  113.000
2  25.0  4.600  2.400   61.000  0.820   75.000
3  53.0  0.250  2.100  145.000  1.030  141.000
4  92.0  0.700  1.300  120.000  0.840  143.000

In [16]:
data1 = [{"age": 35.0, "TSH": 4.672, "T3": 2.025, "TT4": 109.072, "T4U": 0.998, "FTI": 110.788}, 
                  {"age": 63.0, "TSH": 3.500, "T3": 2.500, "TT4": 108.000, "T4U": 0.960, "FTI": 113.000}]

In [17]:
dict1 = {"age": 35.0, "TSH": 4.672, "T3": 2.025, "TT4": 109.072, "T4U": 0.998, "FTI": 110.788}

In [18]:
hypothyroid_classes = {0: 'No hypothyroid disease', 
                       1: 'Primary hypothyroid',
                        2: 'Compensated hypothyroid',
                       3: 'Secondary hypothyroid'}

In [19]:
def hypothyroid_pred(data_lst):  
    scale_max = pd.read_csv('hypodata_max_for_scaling.csv')
    scale_min = pd.read_csv('hypodata_min_for_scaling.csv')
    model = joblib.load("neural_network_numeric_data_model3.pkl")
    y_classes = {'negative': 0, 
           'primary hypothyroid': 1,
            'compensated hypothyroid':2,
           'secondary hypothyroid': 3 }  
    data_arr = pd.DataFrame(data_lst).values
    d_scaled = (data_arr-scale_min.values)/(scale_max.values-scale_min.values)
    pred1 = model.predict(d_scaled) 
    for i in pred1:
        print(hypothyroid_classes[i])
    return pred1

In [20]:
hypothyroid_pred(data1)

No hypothyroid disease
No hypothyroid disease


array([0, 0])

In [21]:
def hypothyroid_pred_app(data_lst):
    scale_max = pd.read_csv('hypodata_max_for_scaling.csv')
    scale_min = pd.read_csv('hypodata_min_for_scaling.csv')
    model = joblib.load("neural_network_numeric_data_model3.pkl")
    hypothyroid_classes = {0: 'No hypothyroid disease',
           1: 'primary hypothyroid',
           2: 'compensated hypothyroid',
           3: 'secondary hypothyroid'}
    data_arr = np.array(data_lst).reshape(-1,6)
    d_scaled = (data_arr-scale_min.values)/(scale_max.values-scale_min.values)
    pred1 = model.predict(d_scaled)
    
    for i in pred1:
        print(hypothyroid_classes[i])
    return pred1

In [22]:
hypothyroid_pred_app([35.0, 4.672, 2.025, 109.072, 0.998, 110.788])

No hypothyroid disease


array([0])

In [23]:
pd.DataFrame(data1).values

array([[110.788,   2.025,   0.998,   4.672, 109.072,  35.   ],
       [113.   ,   2.5  ,   0.96 ,   3.5  , 108.   ,  63.   ]])

In [24]:
pd.DataFrame([dict1])

FTI     T3    T4U    TSH      TT4   age
0  110.788  2.025  0.998  4.672  109.072  35.0

In [25]:
data2 = df_test.loc[:, ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']]

In [26]:
data2.iloc[0:20]

age     TSH     T3      TT4    T4U      FTI
0   35.0   4.672  2.025  109.072  0.998  110.788
1   63.0   3.500  2.500  108.000  0.960  113.000
2   25.0   4.600  2.400   61.000  0.820   75.000
3   53.0   0.250  2.100  145.000  1.030  141.000
4   92.0   0.700  1.300  120.000  0.840  143.000
5   67.0   0.810  2.025   84.000  0.830  101.000
6   60.0   1.200  2.600  117.000  1.310   90.000
7   60.0  27.000  1.800   65.000  0.990   66.000
8   48.0   2.800  2.025  112.000  0.920  121.000
9   27.0   2.600  2.200   94.000  0.890  106.000
10  73.0   4.400  1.200   95.000  1.110   85.000
11  19.0   3.100  2.800  131.000  0.950  138.000
12  72.0   1.100  2.025  131.000  0.500  265.000
13  16.0   4.500  2.025  109.072  0.998  110.788
14  54.0   0.140  3.400  105.000  0.998  110.788
15  39.0   0.060  2.400  148.000  1.070  138.000
16  38.0   1.100  2.200  145.000  1.230  118.000
17  33.0   4.672  2.025  109.072  0.998  110.788
18  45.0   7.400  1.400  108.000  1.080  100.000
19  54.0   1.200  1.700   81.000  0.870   94.000

In [27]:
arr2 = np.array(data2.iloc[0:20].values)

In [28]:
arr2[7]

array([60.  , 27.  ,  1.8 , 65.  ,  0.99, 66.  ])

In [29]:
hypothyroid_pred(arr2[7:9].reshape(-1, 6))

Compensated hypothyroid
No hypothyroid disease


array([2, 0])